name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Cambiar de '18' a '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # Comentado temporalmente hasta que los compañeros suban los tests
      # - name: Run tests
      #   run: npx ng test --watch=false --browsers=ChromeHeadless
      - name: Build project
        run: npx ng build --configuration production
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AT_TP7_DA9D9 }}
          channelId: live
          projectId: at-tp7-da9d9
