name: Angular CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js (usa la versión recomendada para Angular 18: Node 18+)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar pruebas unitarias con Karma/Jasmine
      - name: Run unit tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      # 5. Generar el build de Angular
      - name: Build project
        run: npm run build -- --configuration=production
